# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mainwindow(object):
    def setupUi(self, Mainwindow):
        Mainwindow.setObjectName("Mainwindow")
        Mainwindow.resize(1070, 435)
        self.centralwidget = QtWidgets.QWidget(Mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(20, 30, 181, 20))
        self.name.setObjectName("name")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 121, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 101, 16))
        self.label_2.setObjectName("label_2")
        self.description = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.description.setGeometry(QtCore.QRect(20, 80, 181, 91))
        self.description.setObjectName("description")
        self.start_time = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.start_time.setGeometry(QtCore.QRect(20, 230, 181, 22))
        self.start_time.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 2, 17), QtCore.QTime(0, 0, 0)))
        self.start_time.setObjectName("start_time")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 180, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 260, 54, 12))
        self.label_5.setObjectName("label_5")
        self.end_time = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.end_time.setGeometry(QtCore.QRect(20, 280, 181, 22))
        self.end_time.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 2, 17), QtCore.QTime(0, 0, 0)))
        self.end_time.setObjectName("end_time")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(210, 0, 20, 351))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.push_to_mission = QtWidgets.QPushButton(self.centralwidget)
        self.push_to_mission.setGeometry(QtCore.QRect(20, 310, 181, 23))
        self.push_to_mission.setObjectName("push_to_mission")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 340, 221, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(240, 10, 54, 12))
        self.label_6.setObjectName("label_6")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(240, 30, 811, 321))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(160)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(25)
        self.clean_mission = QtWidgets.QPushButton(self.centralwidget)
        self.clean_mission.setGeometry(QtCore.QRect(20, 360, 181, 23))
        self.clean_mission.setObjectName("clean_mission")
        self.clean_all_mission = QtWidgets.QPushButton(self.centralwidget)
        self.clean_all_mission.setGeometry(QtCore.QRect(650, 360, 91, 23))
        self.clean_all_mission.setObjectName("clean_all_mission")
        Mainwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 23))
        self.menubar.setObjectName("menubar")
        Mainwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Mainwindow)
        self.statusbar.setObjectName("statusbar")
        Mainwindow.setStatusBar(self.statusbar)

        self.retranslateUi(Mainwindow)
        QtCore.QMetaObject.connectSlotsByName(Mainwindow)

    def retranslateUi(self, Mainwindow):
        _translate = QtCore.QCoreApplication.translate
        Mainwindow.setWindowTitle(_translate("Mainwindow", "selfmanagement"))
        self.label.setText(_translate("Mainwindow", "给一个新的任务起名:"))
        self.label_2.setText(_translate("Mainwindow", "描述一下吧:"))
        self.label_3.setText(_translate("Mainwindow", "填一下起止时间:"))
        self.label_4.setText(_translate("Mainwindow", "开始时间"))
        self.label_5.setText(_translate("Mainwindow", "结束时间"))
        self.push_to_mission.setText(_translate("Mainwindow", "推送任务到时间表"))
        self.label_6.setText(_translate("Mainwindow", "任务表"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Mainwindow", "任务名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Mainwindow", "描述"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Mainwindow", "开始时间"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Mainwindow", "结束时间"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Mainwindow", "点击结束"))
        self.clean_mission.setText(_translate("Mainwindow", "清空"))
        self.clean_all_mission.setText(_translate("Mainwindow", "结束所有任务"))
